#!/usr/bin/env python

"""
Usage: insert <file>

Options:
    -h, --help    Show usage info.
"""

from datetime import datetime
from docopt import docopt
from sys import exit
from deepdiff import DeepDiff
from pprint import pprint
import os
import csv
from pyArango.connection import *

if __name__ == '__main__':
    arguments = docopt(__doc__, version='0.1')

filename = arguments["<file>"]

username = os.environ['ARANGODB_USERNAME']
password = os.environ['ARANGODB_PASSWORD']

conn = Connection(username=username, password=password)

db = conn['nrcan']
buildings = db.collections['buildings']

count = 0
update_count = 0

with open(filename, 'r') as csvfile:
    ers_data = csv.DictReader(csvfile, delimiter='|', quotechar='\\')
    for row in ers_data:
        # if count > 5:
        #     exit(0)
        doc = buildings.createDocument()
        house_id = row['HOUSE_ID']
        for key in row.keys():
            doc[key.lower()] = row[key] # death to shouty case!
        ts = datetime.strptime(row['CREATIONDATE'], '%Y-%m-%d %H:%M:%S').timestamp()
        doc.creationdate = ts
        try:
            doc.save()
            count += 1
        except CreationError:
            previous = buildings.fetchDocument(doc['_key'])
            print(f"\nFound an update for {house_id}, changes are:")
            pprint(DeepDiff(doc, previous), indent=2)
            update_count += 1 # This row represents an update to an existing record
            print("\n")

total = count + update_count
print(f"Inserted {count} documents and skipped {update_count} updates. Total processed: {total}")
